### ISSUE TITLE
[Request] Previously selected spool as default value in confirmation dialog

### ISSUE THREAD

**Issue by ranzhe** [malnvenshorn/OctoPrint-FilamentManager#71] opened 2018-01-13 15:46 UTC
Hi. Thanks for adding spool confirmation dialog when "Load and print" is being pressed. Could you please also make previously selected spool as default selected value in select box when that dialog appars?

Thanks a lot!

**Comment by malnvenshorn** [comment] 2018-01-13 16:48
No. Because the purpose of this dialog is to prevent people from accidentally selected the wrong spool, e.g. by forgetting to change the selection within OctoPrint after they switched their spool on the printer. Preselecting any value would counteract with that.

**Comment by ranzhe** [comment] 2018-01-13 17:02
That's obvious. But in fact, if spool hasn't been changed since last print, user will have to look for it in the list and select again, that's a bit annoying. For instance, when there was no confirmation dialog, i could forget (and that happened many times) to change my spool selection before print with the new spool, but if i'd had that dialog appeared (even with wrong spool selected), i'd remember that i have to change my selection.

P.S. Sorry for my English. Sometimes my explanations are not clear enough.

**Comment by malnvenshorn** [comment] 2018-01-13 19:01
Before I added that confirmation dialog I got a lot reports from people forgetting to change the selected spool. The cause was mostly that they wanted to start the print as fast as possible. If I preselect the last spool, as you suggests, what is stopping them from simply clicking print? I think that's what going to happen. Because the dialog always appears, if enabled, people develop an automatism and then we have the same problem again. Because of that I'm not going to change the behavior of the confirmation dialog. I hope you get my point ;-)

**Comment by ranzhe** [comment] 2018-01-13 19:46
Sure, I’ve completely got Your point, and now I think that my original proposal to have previous spool preselected wasn’t so good. But I also ask You to got my point: in the most cases, the user changes spool not very often, and the need to choose a value each time can be irritable, after all.

Perhaps, it will be better to add separated button 'Use previous spool' (optionally - with it’s parameters) to dialog or something like this? Also, i think it will be nice to add some kind of grouping in the select box (by manufacturer or by filament type?), that could make spool look-up process more user-friendly.

**Comment by malnvenshorn** [comment] 2018-01-13 21:27
Sure it's possible to add another checkbox to enable the 'Use previous spool' thing. But to be honest I'm not a fan of this idea. Personally I think this will clutter the settings dialog. The truth is I cannot make this plugin perfect for all users, but since it's open source everyone can modify this plugin to fit there needs.

I understand that the confirmation dialog might be annoying if you rarely change your spool but it is designed that way on purpose. If you don't like it you can disable at any time. To be honest I'm not using it myself. As I sad before, it should stop you from selecting the wrong spool and I think it does a good job. 

> Also, i think it will be nice to add some kind of grouping in the select box (by manufacturer or by filament type?), that could make spool look-up process more user-friendly.

Momentarily the order of the items in the select box is the same as in the spools table. Which means if you sort the table by the vendor the items in the select box will be in the same order.

**Comment by TylonHH** [comment] 2018-01-19 08:03
So I use this PLugin for a while too. At first I was for this idea here. But after some time I'm against it, for the same reason as @malnvenshorn mentioned.
For me, this request can be closed ;-)

**Comment by malnvenshorn** [comment] 2018-01-23 08:06
I'm closing this now, because I'm not going to change the discussed behavior.

**Closed by malnvenshorn** 2018-01-23 08:06 UTC
Labels: type:request

**Comment by szafran81** [comment] 2018-02-01 10:33
Then maybe you can add an option so one can select the behaviour ?
It would make both sides happy.

**Comment by malnvenshorn** [comment] 2018-02-01 14:09
I don't want to make everything customizable  because this would clutter the settings dialog. But as the plugin is open source everyone can modify the filament manager to fit their needs.
