### ISSUE TITLE
Assign colors to spools

### ISSUE THREAD

**Issue by CodilX** [malnvenshorn/OctoPrint-FilamentManager#169] opened 2019-07-17 00:00 UTC
**Is your feature request related to a problem? Please describe.**
I find it difficult to track the actual physical spools I have. Right now I have 6 spools of just Dark Gray PLA with small amounts left in each spool, not counting other filament colors and materials. It's becoming hard and sometimes confusing to easily figure out what spool corresponds to what entry in the manager.

I started adding colored stickers to my spools and adding the same colored emoji block (🟩, 🟥 ... ) to the beginning of every spool title in in the manager.

![Untitled-2](https://user-images.githubusercontent.com/476633/61336553-67874a80-a83a-11e9-9661-b74d43eb7b39.png)

I quickly ran out of emojis, as there are only 7 colored emoji blocks .. I then started adding circle emojis and cutting my stickers round, and I'm running out of that combo now too..

**Describe the solution you'd like**
A color picker for each spool. It could be used for my use case - tagging physical spools to entries in the manager or others might use it to represent the color of the spool. Either way, in my opinion, it would a very useful features to have. 

**Additional context**
It's so quick and easy being able to open up the manager, figure out what spool is best to use for a print and at a glance find the correct spool with the corresponding sticker. It makes managing spools so easy and straight foward. The only thing to make it perfect would be a color picker and not dealing with emojis.

Thank you sooo much for this plugin! I wish I found this plugin waaaay earlier. Great job, keep it up!

**Comment by malnvenshorn** [comment] 2019-08-04 14:45
Duplicate of #153

**Closed as completed by malnvenshorn** 2019-08-04 14:45 UTC
Labels: duplicate
