### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-xf3gH2/psycopg2/ Error! Could not parse output from pip, see plugin_pluginmanager_console.log for generated output

### ISSUE THREAD

**Issue by Airdoo** [malnvenshorn/OctoPrint-FilamentManager#53] opened 2017-12-13 18:34 UTC
#### What were you doing?

Installing 0.5.0

#### What did you expect to happen?

Instal without issue

#### What happened instead?
Failed
#### Link to octoprint.log
https://pastebin.com/a76CxgjF

#### Link to contents of Javascript console in the browser

https://pastebin.com/JXebYQTe ???

#### Further information

[If you have more information which could help me to understand/fix the issue feel free to add them here.] I was attempting to update from the previous revision and also got the same error, I uninstalled both FilamentManager and CostEstimator and attempted to do a fresh install of FilamentManager and CostEstimator. On today's release of OctoPrint.

I have read the FAQ and provided all required information.

**Comment by malnvenshorn** [comment] 2017-12-13 18:59
This is a duplicate of #50. You can find the solution in the mentioned ticket or in the README.

**Closed by malnvenshorn** 2017-12-13 18:59 UTC
Labels: type:possible bug
