### ISSUE TITLE
[Request]

### ISSUE THREAD

**Issue by hamster65** [malnvenshorn/OctoPrint-FilamentManager#109] opened 2018-06-14 19:09 UTC
I always forget to select the right spool before starting the print. It would be a nice feature if filament manager could ask which spool to use.

**Comment by malnvenshorn** [comment] 2018-06-14 19:54
You can enable a confirmation dialog in the settings.

Duplicate of #36, closing.

**Closed** 2018-06-14 19:55 UTC
Labels: status:duplicate, type:request
