### ISSUE TITLE
[Request] Bed Temp offset in filament profile

### ISSUE THREAD

**Issue by arcticash** [malnvenshorn/OctoPrint-FilamentManager#118] opened 2018-08-12 16:50 UTC
I'm not sure if this has already been requested, but i cant seem to find anything relating to this currently open.

We are currently able to set an offset for the hot end temperature in the filament profiles, but it would be nice to be able to set a bed offset too as I have a few filaments that require a lower bed setting as well as a colder nozzle temp to avoid warping the bottom of the prints.

Yes, I know its easy enough to change manually I'm just hoping its a simple addition to add on as the code for the hot end temp is already there! :)

Ash

**Comment by malnvenshorn** [comment] 2018-08-13 06:56
Duplicate of #81

**Closed by malnvenshorn** 2018-08-13 06:56 UTC
Labels: status:duplicate, type:request
